feat: consent norwegian translation
Informasjonsforvaltning/fdk-community-service pull request #82
Opened 2021-05-21 15:11 UTC by jeffreiffers

2021-05-25 07:11 UTC, matsjs approved these changes

2021-05-25 07:11 UTC, matsjs commented on nodebb-theme-fdk/languages/nb/user.json
> +  "ban_account": "Utesteng kont",
```suggestion
  "ban_account": "Utesteng konto",
```

2021-05-25 07:11 UTC, matsjs commented on nodebb-theme-fdk/languages/nb/user.json
> +  "username_taken_workaround": "Brukernavnet du ønsket er opptatt, så vi har endret ditt litt. Du er nå kjent som <strong>%1</string>",
```suggestion
  "username_taken_workaround": "Brukernavnet du ønsket er opptatt, så vi har endret det litt. Du er nå kjent som <strong>%1</string>",
```

2021-05-25 10:39 UTC, shenluna commented on nodebb-theme-fdk/languages/nb/user.json
> +  "consent.title": "Brukervilkår for nettforumet",
```suggestion
  "consent.title": "Samtykke og brukervilkår",
```
Endring av tekst

2021-05-25 10:49 UTC, shenluna commented on nodebb-theme-fdk/languages/nb/user.json
> +  "consent.received": "Do har samtykket til innsamling og behandling av personopplysninger.",
```suggestion
  "consent.received": "Du har samtykket til innsamling og behandling av dine personopplysninger, samt brukervilkårene til nettformuet",
```

2021-05-26 07:29 UTC, shenluna requested changes

2021-05-26 07:29 UTC, shenluna commented on nodebb-theme-fdk/languages/nb/register.json
> +  "cancel_registration": "Avbrytt registreringen",
```suggestion
  "cancel_registration": "Avbryt registreringen",
```

2021-05-26 07:29 UTC, shenluna commented on nodebb-theme-fdk/languages/nb/user.json
> +  "edit-profile": "Edit Profile",
```suggestion
  "edit-profile": "Endre brukerprofil",
```

2021-05-26 07:58 UTC, merged